# Generated by Django 5.0.6 on 2024-06-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_customer_id_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.CharField(choices=[('dark', 'dark'), ('light', 'light'), ('gray', 'gray')], default=None, max_length=50),
        ),
    ]
