# Generated by Django 5.0.4 on 2024-06-10 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_colors_remove_product_colors_product_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='isWishlisted',
        ),
    ]
