# Generated by Django 5.0.6 on 2024-06-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_remove_wishlist_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='color',
            field=models.CharField(default='', max_length=20),
        ),
    ]
