# Generated by Django 5.0.6 on 2024-06-12 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_remove_cart_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='color',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='apps.colors'),
        ),
    ]
