# Generated by Django 5.0.6 on 2024-06-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_cart_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='razor_pay_order_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
