# Generated by Django 5.0.6 on 2024-06-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_orderplaced_razor_pay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='razor_pay_payment_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='razor_pay_payment_signature',
            field=models.CharField(default='', max_length=200),
        ),
    ]
