# Generated by Django 5.0.6 on 2024-06-13 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_orderplaced_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='cart',
        ),
    ]
