# Generated by Django 5.0.6 on 2024-06-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_alter_orderplaced_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='razor_pay_order_id',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='razor_pay_payment_id',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='razor_pay_payment_signature',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
