# Generated by Django 5.0.4 on 2024-07-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_alter_orderplaced_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufactured_by',
            field=models.CharField(default='', max_length=255),
        ),
    ]
