# Generated by Django 5.0.4 on 2024-07-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_product_manufactured_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ids',
            field=models.PositiveBigIntegerField(default=1, editable=False),
        ),
    ]
