# Generated by Django 5.0.4 on 2024-07-14 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_product_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ids',
            new_name='auto_increment_id',
        ),
    ]
